// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruebamvc_1.Models;

namespace pruebamvc_1.Migrations.Contrato
{
    [DbContext(typeof(ContratoContext))]
    [Migration("20220131023209_Contrato")]
    partial class Contrato
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pruebamvc_1.Models.Contrato", b =>
                {
                    b.Property<int>("idcontrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("fecha_final")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("num_contrato")
                        .HasColumnType("int");

                    b.Property<string>("trab_vinculado")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idcontrato");

                    b.ToTable("Contrato");
                });
#pragma warning restore 612, 618
        }
    }
}
