// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruebamvc_1.Models;

namespace pruebamvc_1.Migrations.Trabajador
{
    [DbContext(typeof(TrabajadorContext))]
    [Migration("20220130224306_Trabajador")]
    partial class Trabajador
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pruebamvc_1.Models.Trabajador", b =>
                {
                    b.Property<int>("idtrabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("identificacion")
                        .HasColumnType("int");

                    b.Property<string>("pr_apellido")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pr_nombre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("seg_apellido")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("seg_nombre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tipoidentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idtrabajador");

                    b.ToTable("Trabajador");
                });
#pragma warning restore 612, 618
        }
    }
}
